src/FlipLeaf/Pages/_Manage/Browse.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using FlipLeaf.Storage;
using FlipLeaf.Website;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FlipLeaf.Pages._Manage
{
    public class BrowseModel : PageModel
    {
        private readonly IFileSystem _fileSystem;
        private readonly IGitRepository _git;
        private readonly IWebsiteIdentity _website;

        public BrowseModel(
            IFileSystem fileSystem,
            IGitRepository git,
            IWebsiteIdentity website)
        {
            _git = git;
            _website = website;
            _fileSystem = fileSystem;
            Directories = new List<ManageBrowseItem>();
            Files = new List<ManageBrowseItem>();
        }

        public string Path { get; private set; } = string.Empty;

        public List<ManageBrowseItem> Directories { get; private set; }

        public List<ManageBrowseItem> Files { get; private set; }

        public IActionResult OnGet(string path)
        {
            var directory = _fileSystem.GetItem(path);
            if (directory == null)
            {
                return NotFound();
            }

            if (!_fileSystem.DirectoryExists(directory))
            {
                return NotFound();
            }

            var directories = _fileSystem.GetSubDirectories(directory, prefixDotIncluded: false, prefixUnderscoreIncluded: true)
                .Select(f => new ManageBrowseItem(f, true))
                .OrderBy(f => f.Path.RelativePath)
                .ToList();

            var files = _fileSystem.GetFiles(directory, prefixDotIncluded: false, prefixUnderscoreIncluded: true)
                .Select(f => new ManageBrowseItem(f, false))
                .OrderBy(f => f.Path.RelativePath)
                .ToList();

            this.Path = directory.RelativePath;
            this.Directories = directories;
            this.Files = files;

            //_git.SetLastCommit(directory.RelativePath, this.Files.ToDictionary(f => f.Path.Name, f => f), (f, date) => f.WithCommit(date));

            return Page();
        }

        public IActionResult OnGetDeleteFile(string path)
        {
            var file = _fileSystem.GetItem(path);
            if (file == null)
            {
                return BadRequest();
            }

            if (_fileSystem.FileExists(file))
            {
                _git.Commit(_website.GetCurrentUser(), _website.GetWebsiteUser(), path, $"Delete {path}", remove: true);

                _fileSystem.DeleteFile(file);
            }

            var dir = _fileSystem.GetDirectoryItem(file);

            return RedirectToPage(new { path = dir.RelativePath });
        }

        public IActionResult OnPostCreateDirectory(string path, string name)
        {
            var directory = _fileSystem.GetItem(path);
            if (directory == null || !_fileSystem.DirectoryExists(directory))
            {
                return BadRequest();
            }

            var subDirectory = _fileSystem.Combine(directory, name);

            _fileSystem.EnsureDirectory(subDirectory);

            return RedirectToPage(new { path = subDirectory.RelativePath });
        }

        public IActionResult OnPostCreateFile(string path, string name)
        {
            var directory = _fileSystem.GetItem(path);
            if (directory == null || !_fileSystem.DirectoryExists(directory))
            {
                return BadRequest();
            }

            var file = _fileSystem.Combine(directory, name);

            if (_fileSystem.DirectoryExists(file))
            {
                return BadRequest("A folder with the same name already exists");
            }

            return RedirectToPage("Edit", new { path = file.RelativePath });
        }
    }

    public class ManageBrowseItem
    {
        public ManageBrowseItem(IStorageItem path, bool isDirectory)
        {
            Path = path;
            IsDirectory = isDirectory;
        }

        public bool IsDirectory { get; }

        public IStorageItem Path { get; }

        public DateTimeOffset? LastUpdate { get; set; }

        public ManageBrowseItem WithCommit(LibGit2Sharp.Commit commit)
        {
            if (commit != null)
            {
                LastUpdate = commit.Author.When;
            }

            return this;
        }
    }
}

src/FlipLeaf/Pages/_Manage/Edit.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using FlipLeaf.Markup;
using FlipLeaf.Storage;
using FlipLeaf.Templating;
using FlipLeaf.Website;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Primitives;

namespace FlipLeaf.Pages._Manage
{
    public class EditModel : PageModel
    {
        private readonly IGitRepository _git;
        private readonly IWebsiteIdentity _websiteIdentity;
        private readonly IFormTemplateManager _formTemplateManager;
        private readonly IFileSystem _fileSystem;
        private readonly IYamlMarkup _yaml;

        public EditModel(
            IFileSystem fileSystem,
            IYamlMarkup yaml,
            IGitRepository git,
            IWebsiteIdentity websiteIdentity,
            IFormTemplateManager formTemplateManager)
        {
            _git = git;
            _websiteIdentity = websiteIdentity;
            _formTemplateManager = formTemplateManager;
            _fileSystem = fileSystem;
            _yaml = yaml;
            Path = string.Empty;
        }

        public string Path { get; set; }

        public IDictionary<string, StringValues> Form { get; set; } = new Dictionary<string, StringValues>();

        public FormTemplate FormTemplate { get; set; } = FormTemplate.Default;

        [Display]
        [BindProperty]
        public string? PageContent { get; set; }

        [BindProperty]
        public string? TemplateName { get; set; }

        [Display]
        [BindProperty]
        public string? Comment { get; set; }

        [BindProperty]
        public string? Action { get; set; }

        public IActionResult OnGet(string path, bool form = false, string? template = null)
        {
            var file = _fileSystem.GetItem(path);
            if (file == null)
            {
                return NotFound();
            }

            // form edition reserved to markdown files
            if (!file.IsMarkdown())
            {
                return this.RedirectToPage("EditRaw", new { path });
            }

            if (!_formTemplateManager.TryLoadTemplate(
                template, 
                file, 
                out var templatePage)
                || templatePage == null)
            {
                if (form || template != null)
                {
                    return BadRequest("This file does not supports form editing. No template or invalid template specified");
                }

                return this.RedirectToPage("EditRaw", new { path });
            }

            var formValues = new Dictionary<string, StringValues>();
            foreach (var yamlItem in templatePage.PageHeader)
            {
                if (yamlItem.Value is string yamlString)
                {
                    formValues[yamlItem.Key] = new StringValues(yamlString);
                }
                else if (yamlItem.Value is List<object> yamlArray)
                {
                    formValues[yamlItem.Key] = new StringValues(yamlArray.Select(x => x.ToString()).ToArray());
                }
            }

            this.Path = path;
            this.Form = formValues;
            this.TemplateName = templatePage.Name;
            this.FormTemplate = templatePage.FormTemplate;
            this.PageContent = templatePage.PageContent;

            return Page();
        }

        public IActionResult OnPost(string path)
        {
            var user = _websiteIdentity.GetCurrentUser();
            if (user == null)
            {
                return Unauthorized();
            }

            var file = _fileSystem.GetItem(path);
            if (file == null)
            {
                return NotFound();
            }

            if (!file.IsMarkdown() || string.IsNullOrEmpty(this.TemplateName))
            {
                return BadRequest();
            }

            if (!_formTemplateManager.TryLoadTemplate(this.TemplateName, file, out var templatePage)
                || templatePage == null)
            {
                return BadRequest();
            }

            using (var writer = new StringWriter())
            {
                writer.WriteLine("---");
                writer.WriteLine($"{KnownFields.Template}: {this.TemplateName}");

                foreach (var field in templatePage.FormTemplate.Fields)
                {
                    if (field.Id == null) continue;
                    if (!Request.Form.TryGetValue($"Fields.{field.Id}", out var formValues))
                    {
                        formValues = StringValues.Empty;
                    }

                    switch (field.Type)
                    {
                        case FormTemplateFieldType.Text:
                        case FormTemplateFieldType.Choice:
                        case FormTemplateFieldType.MultiCheckBox:
                            _yaml.WriteHeaderValue(writer, field.Id, formValues, field.DefaultValue?.ToString());
                            break;
                    }
                }

                writer.WriteLine("---");

                writer.Write(PageContent);

                _fileSystem.WriteAllText(file, writer.ToString());
            }

            var websiteUser = _websiteIdentity.GetWebsiteUser();
            _git.Commit(user, websiteUser, path, this.Comment);
            _git.PullPush(websiteUser);

            return RedirectToPage("Show", new { path });
        }
    }
}

src/FlipLeaf/Pages/_Manage/EditRaw.cshtml.cs
using System.ComponentModel.DataAnnotations;
using FlipLeaf.Storage;
using FlipLeaf.Website;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FlipLeaf.Pages._Manage
{
    public class EditRawModel : PageModel
    {
        private readonly IGitRepository _git;
        private readonly IWebsiteIdentity _websiteIdentity;
        private readonly IFileSystem _fileSystem;

        public EditRawModel(
            IFileSystem fileSystem,
            IGitRepository git,
            IWebsiteIdentity websiteIdentity)
        {
            _git = git;
            _websiteIdentity = websiteIdentity;
            _fileSystem = fileSystem;
            Path = string.Empty;
        }

        [BindProperty]
        public string Path { get; set; }

        [Display(Name = "Content")]
        [BindProperty]
        public string? PageContent { get; set; }

        [Display]
        [BindProperty]
        public string? Comment { get; set; }

        [BindProperty]
        public string? Action { get; set; }

        public IActionResult OnGet(string path)
        {

            var file = _fileSystem.GetItem(path);
            if (file == null)
            {
                return NotFound();
            }

            if (_fileSystem.DirectoryExists(file))
            {
                return NotFound();
            }

            var content = string.Empty;
            if (_fileSystem.FileExists(file))
            {
                // read raw content
                content = _fileSystem.ReadAllText(file);
            }

            // handle raw view
            this.Path = path;
            this.PageContent = content;

            return Page();
        }

        public IActionResult OnPost(string path)
        {
            var user = _websiteIdentity.GetCurrentUser();
            if (user == null)
            {
                return Unauthorized();
            }

            var fileItem = _fileSystem.GetItem(path);
            if (fileItem == null)
            {
                return NotFound();
            }

            _fileSystem.WriteAllText(fileItem, this.PageContent ?? string.Empty);

            var websiteUser = _websiteIdentity.GetWebsiteUser();
            _git.Commit(user, websiteUser, path, this.Comment);
            _git.PullPush(websiteUser);

            if (this.Action == "SaveAndContinue")
            {
                return Page();
            }
            else
            {
                return RedirectToPage("Show", new { path });
            }
        }
    }
}

src/FlipLeaf/Pages/_Manage/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FlipLeaf.Pages._Manage
{
    public class IndexModel : PageModel
    {
        public IActionResult OnGet()
        {
            return RedirectToPage("Browse");
        }
    }
}

src/FlipLeaf/Pages/_Manage/Show.cshtml.cs
using System.Collections.Generic;
using FlipLeaf.Readers;
using FlipLeaf.Storage;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FlipLeaf.Pages._Manage
{
    public class ShowModel : PageModel
    {
        private readonly IFileSystem _fileSystem;
        private readonly IEnumerable<IContentReader> _contentReaders;
        private readonly FlipLeafSettings _settings;

        public ShowModel(
            IFileSystem fileSystem,
            IEnumerable<IContentReader> contentReaders,
            FlipLeafSettings settings
            )
        {
            _fileSystem = fileSystem;
            _contentReaders = contentReaders;
            _settings = settings;
        }

        public IActionResult OnGet(string path)
        {
            var file = _fileSystem.GetItem(path);
            if (file == null)
            {
                return NotFound();
            }

            if (!_fileSystem.FileExists(file))
            {
                return NotFound();
            }

            if (file.FamilyFolder != FamilyFolder.None)
            {
                return this.Redirect(path);
            }

            foreach (var reader in _contentReaders)
            {
                if (reader.AcceptFileAsRequest(file, out var requestFile))
                {
                    return this.Redirect($"{_settings.BaseUrl}/" + requestFile.RelativePath);
                }
            }

            return NotFound();
        }
    }
}

src/FlipLeaf/Pages/_Manage/Browse.cshtml
@page "{**path}"
@model FlipLeaf.Pages._Manage.BrowseModel
@{
}

@{ ViewData["Title"] = "Content Manager"; }

@section Styles
{
    <style type="text/css">
        tr .hover-link {
            visibility: hidden;
        }

        tr:hover .hover-link {
            visibility: visible;
        }
    </style>
}

<h3>Content Manager</h3>

<nav aria-label="breadcrumb">
    <manage-breadcrumb path="@Model.Path"></manage-breadcrumb>
</nav>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th></th>
            <th>Last update</th>
        </tr>
    </thead>
    <tbody class="directories">
        @foreach (var item in Model.Directories)
        {
            <tr>
                <td>
                    @if (item.Path.Name.StartsWith('_'))
                    {
                        <i class="fa fa-cog text-primary" aria-hidden="true"></i>
                    }
                    else
                    {
                        <i class="fa fa-folder-o text-primary" aria-hidden="true"></i>
                    }
                    <a asp-route-path="@item.Path.RelativePath">@item.Path.Name</a>
                </td>
                <td></td>
                <td></td>
            </tr>
        }
    </tbody>
    <tbody class="files">
        @foreach (var item in Model.Files)
        {
            <tr>
                <td>
                    <i class="fa fa-file-o text-primary" aria-hidden="true"></i>
                    <a asp-page="Edit" asp-route-path="@item.Path.RelativePath">@item.Path.Name</a>
                </td>
                <td>
                    <span class="hover-link">
                        <a asp-page="Show" asp-route-path="@item.Path.RelativePath">View</a>
                        <a asp-page="Edit" asp-route-path="@item.Path.RelativePath">Edit</a>
                        <a asp-page="EditRaw" asp-route-path="@item.Path.RelativePath">Raw</a>
                        <a asp-page-handler="DeleteFile" asp-route-path="@item.Path.RelativePath">Delete</a>
                    </span>
                </td>
                <td>
                    <span title="@item.LastUpdate?">@item.LastUpdate.ToRelativeTime()</span>
                </td>
            </tr>
        }
    </tbody>
</table>

<h4>Actions</h4>

<form method="post" asp-page-handler="CreateFile" class="form-inline">
    <input type="hidden" name="path" value="@Model.Path" />
    <label for="file_create_name" class="mb-2 mr-sm-2">New file: </label>
    <input id="file_create_name" name="name" class="form-control mb-2 mr-sm-2" placeholder="ex: index.md" />
    <button type="submit" class="btn btn-primary mb-2">Create file</button>
</form>

<form method="post" asp-page-handler="CreateDirectory" class="form-inline">
    <input type="hidden" name="path" value="@Model.Path" />
    <label for="directory_create_name" class="mb-2 mr-sm-2">New folder: </label>
    <input id="directory_create_name" name="name" class="form-control mb-2 mr-sm-2" placeholder="ex: articles" />
    <button type="submit" class="btn btn-primary mb-2">Create directory</button>
</form>

src/FlipLeaf/Pages/_Manage/Edit.cshtml
@page "{**path}"
@model FlipLeaf.Pages._Manage.EditModel
@using FlipLeaf.Templating;

@{ ViewData["Title"] = "Page Editor"; }

@section Styles
{
    <style type="text/css">
        .btn-toolbar > * {
            margin: 0 2px;
        }

        #Content {
            font-size: .9rem;
        }
    </style>
}

<h3>@Model.FormTemplate.Title</h3>

<nav aria-label="breadcrumb">
    <manage-breadcrumb path="@Model.Path"></manage-breadcrumb>
</nav>

<form method="post">
    <input type="hidden" asp-for="TemplateName" />

    <div class="form-row">
        @foreach (var field in Model.FormTemplate.Fields)
        {
            if (field.Id == null) continue;

            var hasValue = Model.Form.TryGetValue(field.Id, out var value);
            var fieldId = $"Fields_{field.Id}";
            var fieldName = $"Fields.{field.Id}";
            var isReadOnly = field.Visibility == FormTemplateFieldVisibility.ReadOnly;

            if (!hasValue && field.DefaultValue != null)
            {
                value = new Microsoft.Extensions.Primitives.StringValues(field.DefaultValue?.ToString());
            }

            if (field.Visibility == FormTemplateFieldVisibility.Hidden)
            {
                foreach (var valueItem in value)
                {
                    <input type="hidden" name="@fieldName" id="@fieldId" value="@valueItem" />
                }
                continue;
            }

            <div class="form-group col-md-@(field.Cols)">
                <label for="Field_@fieldId">
                    @field.Name
                    @if (!string.IsNullOrWhiteSpace(field.Description))
                    {
                        <small class="text-muted mt-1 ml-2">@field.Description</small>
                    }
                </label>
                @if (field.Type == FormTemplateFieldType.Text)
                {
                    <input type="text" id="@fieldId" name="@fieldName" value="@value" class="form-control" readonly="@isReadOnly" />
                }
                else if (field.Type == FormTemplateFieldType.Choice)
                {
                    <select id="@fieldId" name="@fieldName" class="form-control" readonly="@isReadOnly">
                        @if (field.Choices != null)
                        {
                            foreach (var choice in field.Choices)
                            {
                                <option value="@choice.Value" selected="@choice.IsSelected(value)">@choice.Text</option>
                            }
                        }
                    </select>
                }
                else if (field.Type == FormTemplateFieldType.MultiCheckBox)
                {
                    <div>
                        @if (field.Choices != null)
                        {
                            foreach (var choice in field.Choices)
                            {
                                var isChecked = value.Any(v => choice.IsSelected(v));
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="@fieldName" id="@(fieldId)_@choice.Value" value="@choice.Value" checked="@choice.IsSelected(value)" readonly="@isReadOnly">
                                    <label class="form-check-label" for="@(fieldId)_@choice.Value">@choice.Text</label>
                                </div>
                            }
                        }
                    </div>
                }
            </div>
        }
    </div>

    <div class="form-group">
        <label asp-for="PageContent">
            @(Model.FormTemplate.ContentName ?? "PageContent")
            @if (!string.IsNullOrWhiteSpace(Model.FormTemplate.ContentDescription))
            {
                <small class="text-muted mt-1 ml-2">@Model.FormTemplate.ContentDescription</small>
            }
        </label>
        <textarea asp-for="PageContent" rows="10" class="form-control"></textarea>

    </div>

    <div class="form-group">
        <label asp-for="Comment"></label>
        <input asp-for="Comment" class="form-control" />
    </div>

    <div class="btn-toolbar">
        <button type="submit" name="Action" value="Save" class="btn btn-primary">Save</button>
        <button type="submit" name="Action" value="SaveAndContinue" class="btn btn-secondary">Save and Continue</button>
        <a asp-page="Show" asp-route-path="@Model.Path" class="btn btn-link">View</a>
    </div>
</form>

src/FlipLeaf/Pages/_Manage/EditRaw.cshtml
@page "{**path}"
@model FlipLeaf.Pages._Manage.EditRawModel
@{
}

@{ ViewData["Title"] = "Page Editor"; }

@section Styles
{
    <style type="text/css">
        .btn-toolbar > * {
            margin: 0 2px;
        }

        #Content {
            font-size: .9rem;
        }
    </style>
}

<h3>Page Editor</h3>

<nav aria-label="breadcrumb">
    <manage-breadcrumb path="@Model.Path"></manage-breadcrumb>
</nav>

<form method="post">

    <input type="hidden" asp-for="Path" />

    <div class="form-group">
        <label asp-for="PageContent"></label>
        <textarea asp-for="PageContent" rows="20" class="form-control"></textarea>
    </div>

    <div class="form-group">
        <label asp-for="Comment"></label>
        <input asp-for="Comment" class="form-control" />
    </div>

    <div class="btn-toolbar">
        <button type="submit" name="Action" value="Save" class="btn btn-primary">Save</button>
        <button type="submit" name="Action" value="SaveAndContinue" class="btn btn-secondary">Save and Continue</button>
        <a asp-page="Show" asp-route-path="@Model.Path" class="btn btn-link">View</a>
    </div>
</form>

src/FlipLeaf/Pages/_Manage/Index.cshtml
@page
@model FlipLeaf.Pages._Manage.IndexModel

src/FlipLeaf/Pages/_Manage/Show.cshtml
@page "{**path}"
@model FlipLeaf.Pages._Manage.ShowModel

src/FlipLeaf/Pages/_Manage/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.1.7/css/fork-awesome.min.css" integrity="sha256-gsmEoJAws/Kd3CjuOQzLie5Q3yshhvmo7YNtBG7aaEY=" crossorigin="anonymous">
    <title>@ViewData["Title"] - FlipLeaf Manager</title>
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FlipLeaf</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>